/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import Librerias.TextPrompt;
import com.sun.glass.events.KeyEvent;
import conectar_bd.Conexion_consulta;
import java.sql.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public static String privilegio = "", rol = "";
    public int nit;  
    public static String user = "";
    ResultSet rs;
    
    public login() {
        initComponents();
        JLabel1.setVisible(false);
        jComboBoxP.setVisible(false);
        JlabelPrivilegio.setVisible(false);
        cedula.setVisible(false);
        usuario.setVisible(false);
        nombre.setVisible(false);
        pass.setVisible(false);
        JlabelUsuario.setVisible(false);
        JlabelNombre.setVisible(false);
        JlabelCargo.setVisible(false);
        JlabelPass.setVisible(false); 
        btnRegistro.setVisible(false);
        TextPrompt users = new TextPrompt("Ingrese su identificacion", cedula);
        TextPrompt nombres = new TextPrompt("Ingrese usuario", usuario);
        TextPrompt cargos = new TextPrompt("Ingrese su nombre", nombre);
        TextPrompt contraseña = new TextPrompt("****", pass);
       
        TextPrompt name = new TextPrompt("Ingrese usuario", Jnom);
        TextPrompt password = new TextPrompt("****", Jpass);
        
        //AWTUtilities.setWindowOpaque(this, false); // Para hacer transparente el JFrame
        LlenarCombobox();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        Jnom = new javax.swing.JTextField();
        Jpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelRegistro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        JLabel1 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        cedula = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jComboBoxP = new javax.swing.JComboBox();
        JlabelNombre = new javax.swing.JLabel();
        JlabelUsuario = new javax.swing.JLabel();
        JlabelPrivilegio = new javax.swing.JLabel();
        JlabelCargo = new javax.swing.JLabel();
        JlabelPass = new javax.swing.JLabel();
        exito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setBackground(new java.awt.Color(0, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO SESION");

        btnIniciar.setBackground(new java.awt.Color(38, 160, 218));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(204, 255, 255));
        btnIniciar.setText("Inicar Sesión");
        btnIniciar.setBorder(null);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        Jnom.setBackground(new java.awt.Color(0, 153, 204));
        Jnom.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        Jnom.setForeground(new java.awt.Color(255, 255, 255));
        Jnom.setBorder(null);
        Jnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnomActionPerformed(evt);
            }
        });
        Jnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JnomKeyPressed(evt);
            }
        });

        Jpass.setBackground(new java.awt.Color(0, 153, 204));
        Jpass.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        Jpass.setForeground(new java.awt.Color(255, 255, 255));
        Jpass.setBorder(null);
        Jpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JpassKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña:");

        jLabelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        jLabelRegistro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(204, 255, 255));
        jLabelRegistro.setText("Crea tu cuenta aqui");
        jLabelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseEntered(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jnom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jpass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jnom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jpass)
                        .addGap(6, 6, 6)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JLabel1.setBackground(new java.awt.Color(0, 0, 0));
        JLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(0, 0, 0));
        JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1.setText("REGISTRATE");

        btnRegistro.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("REGISTRARSE");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        cedula.setBackground(new java.awt.Color(255, 255, 255));
        cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxP.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxP.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jComboBoxP.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPActionPerformed(evt);
            }
        });

        JlabelNombre.setBackground(new java.awt.Color(51, 51, 51));
        JlabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        JlabelNombre.setText("Nombre Usuario:");

        JlabelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        JlabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelUsuario.setForeground(new java.awt.Color(51, 51, 51));
        JlabelUsuario.setText("NIT:");

        JlabelPrivilegio.setBackground(new java.awt.Color(51, 51, 51));
        JlabelPrivilegio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelPrivilegio.setForeground(new java.awt.Color(51, 51, 51));
        JlabelPrivilegio.setText("Seleccione tu privilegio:");

        JlabelCargo.setBackground(new java.awt.Color(51, 51, 51));
        JlabelCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelCargo.setForeground(new java.awt.Color(51, 51, 51));
        JlabelCargo.setText("Nombre y apellido:");

        JlabelPass.setBackground(new java.awt.Color(51, 51, 51));
        JlabelPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelPass.setForeground(new java.awt.Color(51, 51, 51));
        JlabelPass.setText("Contraseña:");

        exito.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        exito.setForeground(new java.awt.Color(0, 204, 0));
        exito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(JLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(249, 249, 249))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(270, 270, 270))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JlabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlabelCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlabelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(JlabelPrivilegio, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(169, 169, 169))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(169, 169, 169))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jComboBoxP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(127, 127, 127)))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(exito, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(exito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlabelUsuario))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(JlabelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnomActionPerformed

    }//GEN-LAST:event_JnomActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
   
    }//GEN-LAST:event_cedulaActionPerformed
// [0,102,102] 1
    // [153,255,255] 2
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // AGREGAR, REGISTRAR E INSERTAR USUARIOS O PRODUCTOS A UNA BASE DE DATOS
        
        String valorCedula = new String(cedula.getText().trim());
        String valorUsuario = new String(usuario.getText().trim());
        String valorNombre = new String(nombre.getText().trim());
        String valorPass = new String(pass.getText().trim());
        // https://www.youtube.com/watch?v=kBx4q7d2YTs
        if(!valorCedula.isEmpty() && !valorUsuario.isEmpty() && !valorNombre.isEmpty() && !valorPass.isEmpty()){
            // registrarUsuario(valorCedula, valorUsuario, valorNombre, valorPass);
            try {
                RegistroUsuario registroUsuario = new RegistroUsuario();
                registroUsuario.registrarUsuario(valorCedula, valorUsuario, valorNombre, valorPass);
                cedula.setText("");
                usuario.setText("");
                nombre.setText("");
                pass.setText("");
                exito.setText("Su registro fue exitoso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hay un error con el servidor", "Alerta!", JOptionPane.CANCEL_OPTION);
            }
      
        } else {
            JOptionPane.showMessageDialog(this, "No dejes campos vacios", "Alerta!", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

 /*   
  
    private void registrarUsuario(String Cedula, String Usuario, String Nombre, String Pass){
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_inventario", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into ejemplo values(?,?,?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, privilegio.trim());
            pst.setString(3, Cedula);   
            pst.setString(4, Usuario);  
            pst.setString(5, Nombre);
            pst.setString(6, Pass);
            pst.executeUpdate();
            //jComboBoxP.setSelectedItem(0);
            cedula.setText("");
            usuario.setText("");
            nombre.setText("");
            pass.setText("");
            JOptionPane.showMessageDialog(null, "Registro Exitoso!");
            exito.setText("Su registro fue exitoso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Upps, hay un error en el servidor", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
 */
 
 
    private void ControlUsuario(){
          try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_inventario", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT count(id) FROM ejemplo WHERE user = ?");
            
          //  pst.setString(1, "0");
            pst.setString(1, usuario.getText().trim());  
            rs = pst.executeQuery();
                        
            if(rs.next()){
                //return rs.getInt(1);
            }      
            //return 1;
           
            //jComboBoxP.setSelectedItem(0);
            /*cedula.setText("");
            usuario.setText("");
            nombre.setText("");
            pass.setText("");
            JOptionPane.showMessageDialog(null, "Registro Exitoso!");
            exito.setText("Registro Exitoso!");*/
        } catch (Exception e) {
             //return 1;
        }
    }
    
     private void LlenarCombobox(){
         try {
           // Nombre = jComboBox1.getSelectedItem().toString();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_inventario", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT privilegio_user FROM privilegio");
          //  pst.setString(1, clave.getText()); 
 //         SELECT Nombre From usuario WHERE nit
           
            /*pst.setString(1, Nombre);*/
            
            rs = pst.executeQuery();
         
            //jComboBoxP.addItem("SELECCIONE UNA OPCION...");
           
          //  login var = new login();
           // int nit = var.nit;
           //   System.out.println("IMPRIMIENDO PRINCIPAL "+nit);
            if(/*rs.next()*/ true){  
              //getNit getnit = new getNit(nit);
              //getnit.consultar();
                
                //  ENVIAR LA VARIABLE NIT PARA HACI HACER LA CONSULTA PARA MOSTRAR EL NOMBRE
              while(rs.next()){
                  System.out.println(rs.getString("privilegio_user")); // MOSTRAR EL PRODUCTO
                  jComboBoxP.addItem(rs.getString("privilegio_user"));
                 
                //  rs.next();
              }
 
            } else {
                 JOptionPane.showMessageDialog(null, "No existe este producto");
            }
           
        } catch (Exception e) {
           System.out.println(e.getMessage());
        }
    }
     
    public void acceder(String usuario, String pass){
        // LOGIN CON BASE DE DATOS
        //String cap = ""; // capturar el tipo de usuario
        if(!usuario.isEmpty() && !pass.isEmpty()){
            String sql = "SELECT nit, privilegio, user FROM ejemplo WHERE user='"+usuario+"' AND password='"+pass+"'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);  
                
                    //  if(!rs.equals("")) JOptionPane.showMessageDialog(null, "No existe sus datos");    
                    if(rs.next()){  //  while(rs.next()){  // Compras
                       nit = rs.getInt("nit");
                       privilegio  = rs.getString("privilegio");
                       user = rs.getString("user");
                       rol = rs.getString("privilegio");
                       // password = rs.getString("password");
                       System.out.println(nit);
                       System.out.println(privilegio);
                       System.out.println(user);
                       
                       // if(user.equals(usuario) && password.equals(pass)){
                        /*
                       if(privilegio.equals("Administrador")){
                                JOptionPane.showMessageDialog(null, "BIENVENIDO!! " + "\nSeñor Administrador");
                                   //   new getNit(nit);
                                Principal principal = new Principal();
                                //principal.
                                principal.setVisible(true);   
                                //principal
                                dispose();
                                } else if(privilegio.equals("Vendedor")){
                                     JOptionPane.showMessageDialog(null, "BIENVENIDO!! " + "\nVendedor");
                                         //   new getNit(nit);
                                Principal_vendedor principal1 = new Principal_vendedor();
                                principal1.setVisible(true);   
                                //principal
                                dispose();
                            }
                            */
                            
                            JOptionPane.showMessageDialog(null, "BIENVENIDO!! " + rol);
                            Principal principal = new Principal();
                            principal.setVisible(true);       
                            dispose();
                            
                            
                        } else if(!rs.next()){
                        JOptionPane.showMessageDialog(this, "La credenciales no son validas", "Upps!", JOptionPane.CANCEL_OPTION);
                        }
                  // }
                  
            } catch (Exception ex) {
                // Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error en el servidor", "Alerta!", JOptionPane.ERROR_MESSAGE);
            }   
        } else {
            JOptionPane.showMessageDialog(this, "No dejes campos vacios", "Alerta!", JOptionPane.CANCEL_OPTION);
        }
    }
     
    
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        String name = new String (Jnom.getText()); 
        String password = new String (Jpass.getPassword());
        acceder(name, password);
    }//GEN-LAST:event_btnIniciarActionPerformed
    
    private void jLabelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseClicked
        jLabelRegistro.setForeground(new java.awt.Color(255,255,255)); // SELECCIONADO
        JLabel1.setVisible(true);
        jComboBoxP.setVisible(true);
        JlabelPrivilegio.setVisible(true);
        cedula.setVisible(true);
        usuario.setVisible(true);
        nombre.setVisible(true);
        pass.setVisible(true);
        JlabelUsuario.setVisible(true);
        JlabelNombre.setVisible(true);
        JlabelCargo.setVisible(true);
        JlabelPass.setVisible(true);
        btnRegistro.setVisible(true);
    }//GEN-LAST:event_jLabelRegistroMouseClicked

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void JpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JpassKeyPressed
        // VALIDAR EL ENTER  para el input de PASSWORD
        String  name = new String (Jnom.getText()); 
        String password = new String (Jpass.getPassword());
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Jpass.requestFocus();
            acceder(name, password);
        }
    }//GEN-LAST:event_JpassKeyPressed

    private void JnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JnomKeyPressed
        // VALIDAR EL ENTER para el input de NOMBRE
        String  name = new String (Jnom.getText()); 
        String password = new String (Jpass.getPassword());
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Jnom.requestFocus();
            acceder(name, password);
        }
    }//GEN-LAST:event_JnomKeyPressed

    private void jComboBoxPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPActionPerformed
        // TODO add your handling code here:
         // categoria = jECategoria.getSelectedItem().toString();
        privilegio = jComboBoxP.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxPActionPerformed
   
    private void ColorItem(JLabel label){
        label.setForeground(new java.awt.Color(204,255,255)); // SELECCIONADO
    }
    private void QuitarColorItem(JLabel label){
        label.setForeground(new java.awt.Color(255,255,255)); // AZUL CLARO
    }
    
    private void jLabelRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseEntered
        // TODO add your handling code here:
        ColorItem(jLabelRegistro);
    }//GEN-LAST:event_jLabelRegistroMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        QuitarColorItem(jLabelRegistro);
    }//GEN-LAST:event_jPanel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JlabelCargo;
    private javax.swing.JLabel JlabelNombre;
    private javax.swing.JLabel JlabelPass;
    private javax.swing.JLabel JlabelPrivilegio;
    private javax.swing.JLabel JlabelUsuario;
    private javax.swing.JTextField Jnom;
    private javax.swing.JPasswordField Jpass;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel exito;
    private javax.swing.JComboBox jComboBoxP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    Conexion_consulta cc = new Conexion_consulta();
    Connection cn = cc.conexion();
    
  /* public String getNombre(){
      return nombre_usuario; // agarra los datos que esten en nombre
   }   
   public void setNombre(String nombre_usuario){
       
   }
   public String getContraseña() {
     return contraseña_usuario;
   }
   public void setContraseña(String contraseña_usuario) {
      login.nombre_usuario = nombre_usuario;	
   }*/

  
}